// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8vSDXvp5BR7Ef6Re1Ba1ukEKkVXmYrg',
    appId: '1:1010113441957:android:17637d4f76cbd98a255d4c',
    messagingSenderId: '1010113441957',
    projectId: 'auth-5f458',
    storageBucket: 'auth-5f458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrBy1xigwF17RNpP677J61s09xI7c6nAs',
    appId: '1:1010113441957:ios:bac34bd1f69ac0b0255d4c',
    messagingSenderId: '1010113441957',
    projectId: 'auth-5f458',
    storageBucket: 'auth-5f458.appspot.com',
    iosBundleId: 'com.example.mccLab23dec23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrBy1xigwF17RNpP677J61s09xI7c6nAs',
    appId: '1:1010113441957:ios:27272c5c5fd92d09255d4c',
    messagingSenderId: '1010113441957',
    projectId: 'auth-5f458',
    storageBucket: 'auth-5f458.appspot.com',
    iosBundleId: 'com.example.mccLab23dec23.RunnerTests',
  );
}
